### ISSUE TITLE
Remove the reference to collective.externalimageeeditor

### ISSUE THREAD

**Issue by kiorky** [collective/collective.aviary#2]
I am totally against the fact that externalimageeditor is complex or bloat because it supports multiple backends.

At the end, you implement your own backend totally because the common interface is fairly stupid.

So i suggest for you to totally remove the references to it or at least remove the KISS sentence which is incorrect and unrelated.

If you dislike this addon, it's ok, but fudding on its design by non founded arguments is just crap.

/cc @ebrehault @toutpt @jpcw

**Comment by hvelarde** [comment]
keep calm; done in c9a5cea1be86d17bd4cab112c9a778b07b0efd80

**Comment by kiorky** [comment]
Reference are not removed and still aggressives and unargumented against collective.externalimageeditor.

In collective.externalimageeditor, you have all the liberty to make your webservice integration, you have to write from begin to end the browserview serving your backend, so you are just lying telling that c.externalimageeditor does not let you control all the features aviary can provide.

**Comment by tdesvenain** [comment]
Hi @hvelarde , i am not a maintainer of this product, but at my point of view you should avoid explanations in your documentation relating on what does not work as you want in similar products, wich can be inaccurate and are very hard to "maintain", as those products can change.

By example, in the documentation of https://github.com/collective/collective.upload you write that collective.quickupload do not work with dexterity, but this is fixed for years https://github.com/collective/collective.quickupload/commit/8eb3c4f151fd194700480e66801ecbcd3cabaf1f (it even works on dexterity-only sites)

**Comment by hvelarde** [comment]
@tdesvenain thanks; it's fixed: https://github.com/collective/collective.upload#not-entirely-unlike

**Comment by hvelarde** [comment]
for me, this issue is closed: 2d889ad2f0a1bbb4a402340cb530402622cfce5e

**Comment by kiorky** [comment]
Sorry but externalimageeditor at the date of the upload supported aviary, its not because i have not the time yet to repair the aviary support that externalimageeditor doesnt support it.
So please stop amending other products trying to gain publicity on yours.
This is so unpolitly awkward.

**Comment by kiorky** [comment]
I would like that you either you fix your quoting about externalimageeditor to not be biased or just remove the citation about this product.

**Comment by hvelarde** [comment]
@kiorky support for Aviary in externalimageeditor is broken as I reported previously:

https://github.com/collective/collective.externalimageeditor/issues/2

feel free to amend the reference in this package when you fix it.

happy new year!

**Comment by kiorky** [comment]
Maybe broken but support is there, if you still continue and persist to fud  and grab free critisim on others work, you ll  reap the whirlwind.
